language: node_js
os:
  - linux
dist: xenial
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  provider: pages
  strategy: git
  cleanup: false
  local_dir: docs/.vuepress/dist
  keep_history: false
  token: ${{secrets.GIT_TOKEN}}
  on:
    branch: master
