name: Build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Prepare NodeJS
      run: yarn
    - name: Build docs
      run: |
          yarn docs:build
          # cd docs/.vuepress/dist
          # git init
          # git add -A
          # git commit -m 'deploy for GitHub Pages'
    #- name: Push changes to repository
    #  run: git push -f git@github.com:feathersjs-offline/docs.git master:gh-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
        user_name: "mhillerstrom"
        user_email: "michael@hillerstrom.name"
        commit_message: "deploy for GitHub Pages"
